implement role model, service, dao, UserDetailsServiceImp
IwalkInSilence/Football_project pull request #10
Opened 2021-02-22 12:56 UTC by IwalkInSilence

change user model and user dao
added dependency
change appconfig

2021-02-22 15:49 UTC, YuraBondarenko approved these changes

2021-02-22 16:28 UTC, RomanDubovskyi requested changes

2021-02-22 16:28 UTC, RomanDubovskyi commented on src/main/java/project/cinema/model/Role.java
> +    private Roles role;
```suggestion
    private RoleName role;
```

2021-02-22 16:28 UTC, RomanDubovskyi commented on src/main/java/project/cinema/model/User.java
> +    private List<Role> roles;
```suggestion
    private Set<Role> roles;
```

2021-02-22 16:28 UTC, RomanDubovskyi commented on src/main/java/project/cinema/security/UserDetailsServiceImp.java
> +        User user = userService.findByEmail(email).get();
let's throw UsernameNotFoundException instead of NoSuchElement

2021-02-22 16:28 UTC, RomanDubovskyi commented on src/main/java/project/cinema/security/UserDetailsServiceImp.java
> +        if (user != null) {
can user be null?

2021-02-23 08:10 UTC, RomanDubovskyi approved these changes

2021-02-23 08:10 UTC, RomanDubovskyi commented on src/main/java/project/cinema/security/UserDetailsServiceImp.java
> +        builder = org.springframework.security.core.userdetails.User.withUsername(email);
```suggestion
        UserBuilder builder = org.springframework.security.core.userdetails.User.withUsername(email);
```

2021-02-25 16:57 UTC, merged